**Numpy**

In [ ]:
import numpy as np

**Multiply Numpy arrays**

In [ ]:
NumP_arr=np.array([[1,2,3],[4,5,6]])
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
print(NP1)
NP2

Using '@' to multiply the matrices.

In [ ]:
MNP1=NP1@NP2
MNP1

Using '*' is for multiply each lonely(element by element) value of NP1 with NP2.

In [ ]:
MNP2=NP1*NP2
MNP2

Instead of using '@',we can use np.dot() method to multiply matrices NP1 with NP2 (MNP1==MNP3).

In [ ]:
MNP3=np.dot(NP1,NP2)
MNP3

Instead of using '*', we can use np.multiply method to multiply each lonely(element by element) value of NP1 with NP2 (MNP2==MNP4).

In [16]:
MNP4=np.multiply(NP1,NP2)
MNP4


array([[ 3, 12],
       [20, 35]])

**Sum and Sub Numpy arrays**

In [17]:
Sum1=NP1+NP2
Sum1

array([[ 4,  7],
       [ 9, 12]])

In [18]:
Sub1=NP1-NP2
Sub1

array([[-2, -1],
       [-1, -2]])

Or we can use np.subtract method instead of '-':

In [19]:
Sub2=np.subtract(NP1,NP2)
Sub2

array([[-2, -1],
       [-1, -2]])

Sum the all elements

In [21]:
np.sum(NP1)

13

Add number c to all elements in NP1(Broadcasting expending added array)

In [23]:
Board_Nump=NP1+3#[3,3]
                #[3,3]
Board_Nump

array([[4, 6],
       [7, 8]])

In [25]:
NP3=np.array([[3,4]])
NP1+NP3  #[[1 3] + [[3,4]]
         #[4 5]]   [3,4]]

array([[4, 7],
       [7, 9]])

**Divide Numpy arrays**

In [32]:
D = np.divide(NP1,2)#Array of floats numbers
print("D:",D)
int_array=np.floor_divide(NP1,2)
print("int_array:",int_array)

D: [[0.5 1.5]
 [2.  2.5]]
int_array: [[0 1]
 [2 2]]


**Numpy has Math functions**

In [37]:
np.math.sqrt(10)

3.1622776601683795

**Generate Normal Distribution**

generate array of random numbers of the form of normal distribution values:

In [38]:
ND=np.random.standard_normal((3,4))#3 Rows ,4 Columns
ND

array([[ 2.04989461,  0.8689095 , -0.92234953, -0.03852645],
       [-1.18091964,  0.68839326,  0.4340177 , -1.27355317],
       [ 1.17841525, -0.53975743, -2.252935  ,  1.63003417]])

**Generate Uniform Distribution**

In [39]:
UD=np.random.uniform(1,12,(3,4))
UD

array([[ 7.28640367,  7.08506577,  3.79414501,  2.26546751],
       [11.28923119, 10.20127121, 11.77078925,  7.02280501],
       [ 5.32771527,  3.81451064, 10.02061601,  2.31906591]])

In [41]:
np.random.rand()#Generate floats numbers
Random_int=np.random.randint(1,50,(2,5))#Generate integer numbers
Random_int

array([[41, 19, 15, 44, 35],
       [29, 39, 35, 48, 33]])

Build array of zeros or ones

In [43]:
z=np.zeros((3,4))
print("zeros:",z)
ones=np.ones((3,4))
ones

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Filtering arrays**

In [46]:
Filter_Ar=np.logical_and(Random_int>30, Random_int<50)#returning array in form of True or False if the values are in range.
Filter_Ar

array([[ True, False, False,  True,  True],
       [False,  True,  True,  True,  True]])

If we want to see the values that made the logical_and True:

In [47]:
F_Random_int=Random_int[Filter_Ar]
F_Random_int

array([41, 44, 35, 39, 35, 48, 33])

**Statistics using Numpy**

Average:

In [48]:
Data_N=np.array([1,3,4,5,7,9])
Mean_N=np.mean(Data_N)
Mean_N

4.833333333333333

Median:

In [49]:
Median_N=np.median(Data_N)
Median_N

4.5

Variance:

In [50]:
Var_N=np.var(Data_N)
Var_N

6.805555555555556

Standard deviation:1 dim arrays

In [51]:
SD_N=np.std(Data_N)#1 dim
SD_N

2.608745973749755

Calculate for >2 dim arrays:

In [54]:
#NumP_arr=np.array([[1,2,3],[4,7,6]])
#axis=1 --> will calculate Variance Row by Row
Var_Nump1=np.var(NumP_arr,axis=1)
print("Var_Nump1",Var_Nump1)
#axis=0 --> will calculate Variance Columns by Columns
Var_Nump2=np.var(NumP_arr,axis=0)
Var_Nump2

Var_Nump1 [0.66666667 0.66666667]


array([2.25, 2.25, 2.25])