**Numpy**

In [55]:
import numpy as np

**Multiply Numpy arrays**

In [56]:
NumP_arr=np.array([[1,2,3],[4,5,6]])
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
print(NP1)
NP2

[[1 3]
 [4 5]]


array([[3, 4],
       [5, 7]])

Using '@' to multiply the matrices.

In [57]:
MNP1=NP1@NP2
MNP1

array([[18, 25],
       [37, 51]])

Using '*' is for multiply each lonely(element by element) value of NP1 with NP2.

In [58]:
MNP2=NP1*NP2
MNP2

array([[ 3, 12],
       [20, 35]])

Instead of using '@',we can use np.dot() method to multiply matrices NP1 with NP2 (MNP1==MNP3).

In [59]:
MNP3=np.dot(NP1,NP2)
MNP3

array([[18, 25],
       [37, 51]])

Instead of using '*', we can use np.multiply method to multiply each lonely(element by element) value of NP1 with NP2 (MNP2==MNP4).

In [60]:
MNP4=np.multiply(NP1,NP2)
MNP4


array([[ 3, 12],
       [20, 35]])

**Sum and Sub Numpy arrays**

In [61]:
Sum1=NP1+NP2
Sum1

array([[ 4,  7],
       [ 9, 12]])

In [62]:
Sub1=NP1-NP2
Sub1

array([[-2, -1],
       [-1, -2]])

Or we can use np.subtract method instead of '-':

In [63]:
Sub2=np.subtract(NP1,NP2)
Sub2

array([[-2, -1],
       [-1, -2]])

Sum the all elements

In [64]:
np.sum(NP1)

13

Add number c to all elements in NP1(Broadcasting expending added array)

In [65]:
Board_Nump=NP1+3#[3,3]
                #[3,3]
Board_Nump

array([[4, 6],
       [7, 8]])

In [66]:
NP3=np.array([[3,4]])
NP1+NP3  #[[1 3] + [[3,4]]
         #[4 5]]   [3,4]]

array([[4, 7],
       [7, 9]])

**Divide Numpy arrays**

In [67]:
D = np.divide(NP1,2)#Array of floats numbers
print("D:",D)
int_array=np.floor_divide(NP1,2)
print("int_array:",int_array)

D: [[0.5 1.5]
 [2.  2.5]]
int_array: [[0 1]
 [2 2]]


**Numpy has Math functions**

In [68]:
np.math.sqrt(10)

3.1622776601683795

**Generate Normal Distribution**

generate array of random numbers of the form of normal distribution values:

In [69]:
ND=np.random.standard_normal((3,4))#3 Rows ,4 Columns
ND

array([[-2.28264144,  0.63690126, -1.36901876, -0.98757995],
       [-0.83059066, -0.37559857,  1.78218137, -0.46627741],
       [ 0.53309369, -1.44017147, -0.03617272, -0.90936807]])

**Generate Uniform Distribution**

In [70]:
UD=np.random.uniform(1,12,(3,4))
UD

array([[ 2.34458109, 10.87315297,  1.42190234,  4.47420937],
       [ 1.70447338,  4.6527659 ,  4.83935007,  5.60594548],
       [ 1.15749311,  9.10182589,  1.24240749, 10.926394  ]])

In [71]:
np.random.rand()#Generate floats numbers
Random_int=np.random.randint(1,50,(2,5))#Generate integer numbers
Random_int

array([[10, 45,  1, 28, 19],
       [ 5, 26, 47, 11, 30]])

Build array of zeros or ones

In [72]:
z=np.zeros((3,4))
print("zeros:",z)
ones=np.ones((3,4))
ones

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Filtering arrays**

In [73]:
Filter_Ar=np.logical_and(Random_int>30, Random_int<50)#returning array in form of True or False if the values are in range.
Filter_Ar

array([[False,  True, False, False, False],
       [False, False,  True, False, False]])

If we want to see the values that made the logical_and True:

In [74]:
F_Random_int=Random_int[Filter_Ar]
F_Random_int

array([45, 47])

**Statistics using Numpy**

Average:

In [75]:
Data_N=np.array([1,3,4,5,7,9])
Mean_N=np.mean(Data_N)
Mean_N

4.833333333333333

Median:

In [76]:
Median_N=np.median(Data_N)
Median_N

4.5

Variance:

In [77]:
Var_N=np.var(Data_N)
Var_N

6.805555555555556

Standard deviation:1 dim arrays

In [78]:
SD_N=np.std(Data_N)#1 dim
SD_N

2.608745973749755

Calculate for >2 dim arrays:

In [79]:
#NumP_arr=np.array([[1,2,3],[4,7,6]])
#axis=1 --> will calculate Variance Row by Row
Var_Nump1=np.var(NumP_arr,axis=1)
print("Var_Nump1",Var_Nump1)
#axis=0 --> will calculate Variance Columns by Columns
Var_Nump2=np.var(NumP_arr,axis=0)
Var_Nump2

Var_Nump1 [0.66666667 0.66666667]


array([2.25, 2.25, 2.25])